// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFGuVwXrxsqXZE87HjZLAK50QYH48YjRI',
    appId: '1:8264374381:web:965c17d843d9d0810fc764',
    messagingSenderId: '8264374381',
    projectId: 'todo-app-48cc9',
    authDomain: 'todo-app-48cc9.firebaseapp.com',
    storageBucket: 'todo-app-48cc9.firebasestorage.app',
    measurementId: 'G-PPC8Z8MV8Z',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUqSUVdwQZN9QyeN17W2wLGwJrj_1M5vg',
    appId: '1:8264374381:ios:b146c059c02974ae0fc764',
    messagingSenderId: '8264374381',
    projectId: 'todo-app-48cc9',
    storageBucket: 'todo-app-48cc9.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUqSUVdwQZN9QyeN17W2wLGwJrj_1M5vg',
    appId: '1:8264374381:ios:b146c059c02974ae0fc764',
    messagingSenderId: '8264374381',
    projectId: 'todo-app-48cc9',
    storageBucket: 'todo-app-48cc9.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFGuVwXrxsqXZE87HjZLAK50QYH48YjRI',
    appId: '1:8264374381:web:85c35903d1e790810fc764',
    messagingSenderId: '8264374381',
    projectId: 'todo-app-48cc9',
    authDomain: 'todo-app-48cc9.firebaseapp.com',
    storageBucket: 'todo-app-48cc9.firebasestorage.app',
    measurementId: 'G-9RV93ZSMNK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUfVTb5H8R9U26-oPCwSH-h6rkqdQEkE4',
    appId: '1:8264374381:android:982c5a94b9ad7a690fc764',
    messagingSenderId: '8264374381',
    projectId: 'todo-app-48cc9',
    storageBucket: 'todo-app-48cc9.firebasestorage.app',
  );

}